### ISSUE TITLE
in release mode it crash

### ISSUE THREAD

**Issue by vinurs** [svdo/CLJSReactNativeNavigation#7]
it seems that in develope mode, this work, but when i release it as as apk or ipa, it crash

**Comment by vinurs** [comment]
oh i found in shadow-cljs compile it works ok, but in shadow-cljs release, it cause crash

**Comment by svdo** [comment]
For future reference: this turned out to be because the user's source code was missing some `^js` type hints, which was revealed by running `shadow-cljs check <target-name>`.
